<div>
    <!-- List -->
    <div class="flex justify-center items-center min-h-screen bg-gray-100 dark:bg-neutral-900 px-4 py-10">
        <div class="w-full max-w-3xl bg-white dark:bg-neutral-800 shadow-lg rounded-2xl p-8 space-y-6">
            <h2 class="text-2xl font-semibold text-gray-800 dark:text-white mb-4">License Information</h2>
    
            @php
                $infoItems = [
                    'Client Name' => $licens->client_name,
                    'Status' => $licens->status,
                    'Key' => $licens->license_key,
                    'Duration Time' => $licens->start_date . ' - ' . $licens->end_date,
                    'Generated By' => $licens->user->name ?? 'N/A',
                    'Modules' => implode(' - ', array_filter([
                        $licens->autoDialerModules->name ?? null,
                        $licens->autoDistributorModuales->name ?? null,
                        $licens->evaluationModuales->name ?? null
                    ])),
                    'Description' => $licens->description ?? 'No description',
                ];
            @endphp
    
            @foreach ($infoItems as $label => $value)
                <div class="flex flex-col sm:flex-row justify-between border-b border-gray-200 dark:border-neutral-700 pb-3">
                    <span class="text-sm font-medium text-gray-500 dark:text-neutral-400 w-40">{{ $label }}</span>
                    <span class="text-sm text-gray-800 dark:text-neutral-200">{{ $value }}</span>
                </div>
            @endforeach
        </div>
    </div>
    
    <!-- End List -->
</div>